apiVersion: apps/v1
kind: Deployment
metadata:
  name: giftfrontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: giftfrontend
  template:
    metadata:
      labels:
        app: giftfrontend
    spec:
      containers:
        - name: giftfrontend
          image: us.icr.io/sn-labs-goncalodamas/giftfrontend:latest
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: giftfrontend
  ports:
    - port: 80
      targetPort: 80
  type: NodePort